clients:
  - configPath: "C:/Users/Batuhan/Documents/GitHub/DistributedReadWrite/smgrpctest/src/main/resources/sm3.yaml"
    inputPath: "C:/Users/Batuhan/Documents/GitHub/DistributedReadWrite/smgrpctest/src/main/resources/_multiClientIn1.txt"
    outputPath: "C:/Users/Batuhan/Documents/GitHub/DistributedReadWrite/smgrpctest/src/main/resources/_multiClientCommonOut.txt"

  - configPath: "C:/Users/Batuhan/Documents/GitHub/DistributedReadWrite/smgrpctest/src/main/resources/sm3.yaml"
    inputPath: "C:/Users/Batuhan/Documents/GitHub/DistributedReadWrite/smgrpctest/src/main/resources/_multiClientIn2.txt"
    outputPath: "C:/Users/Batuhan/Documents/GitHub/DistributedReadWrite/smgrpctest/src/main/resources/_multiClientCommonOut.txt"

  - configPath: "C:/Users/Batuhan/Documents/GitHub/DistributedReadWrite/smgrpctest/src/main/resources/sm3.yaml"
    inputPath: "C:/Users/Batuhan/Documents/GitHub/DistributedReadWrite/smgrpctest/src/main/resources/_multiClientIn3.txt"
    outputPath: "C:/Users/Batuhan/Documents/GitHub/DistributedReadWrite/smgrpctest/src/main/resources/_multiClientCommonOut.txt"